<?php

/**
 * Implements hook_field_schema().
 */
function sse_contactfield_field_schema($field) {
  return [
    'columns' => [
      'type' => [
        'type' => 'varchar',
        'length' => 31,
        'not null' => FALSE
      ],
      'val' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE
      ],
      'title' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE
      ]
    ]
  ];
}
